### ISSUE TITLE
Hi, I have a problem when using this

### ISSUE THREAD

**Issue by tylaar** [brianjcj/auto-complete-clang#3]
When I hit "ctl + tab", I got a "invalid 3th argument", and I trace down this problem to a function in auto-complete-clang.el , which is called ac-clang-candidate. It is said that the 3th argument of the apply function inside this ac-clang-candidate is invalidate. However , I cannot figure out why...

**Comment by brianjcj** [comment]
This is because your clang version is too old. It doesn't support '-' option
which can input the source file from standard input (then it is no longer
necessary to save the buffer before completion).

Either upgrade your clang, or you can add the following settings to your
.emacs

(setq ac-clang-auto-save t)
